BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[EL_ACCOUNTS] (
    [ID] NVARCHAR(1000) NOT NULL,
    [USER_ID] NVARCHAR(1000) NOT NULL,
    [TYPE] NVARCHAR(1000) NOT NULL,
    [PROVIDER] NVARCHAR(1000) NOT NULL,
    [PROVIDER_ACCOUNT_ID] NVARCHAR(1000) NOT NULL,
    [REFRESH_TOKEN] TEXT,
    [ACCESS_TOKEN] TEXT,
    [EXPIRES_AT] INT,
    [TOKEN_TYPE] NVARCHAR(1000),
    [SCOPE] NVARCHAR(1000),
    [ID_TOKEN] TEXT,
    [SESSION_STATE] NVARCHAR(1000),
    CONSTRAINT [EL_ACCOUNTS_pkey] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [EL_ACCOUNTS_PROVIDER_PROVIDER_ACCOUNT_ID_key] UNIQUE NONCLUSTERED ([PROVIDER],[PROVIDER_ACCOUNT_ID])
);

-- CreateTable
CREATE TABLE [dbo].[EL_SESSIONS] (
    [ID] NVARCHAR(1000) NOT NULL,
    [SESSION_TOKEN] NVARCHAR(1000) NOT NULL,
    [USER_ID] NVARCHAR(1000) NOT NULL,
    [EXPIRES] DATETIME2 NOT NULL,
    CONSTRAINT [EL_SESSIONS_pkey] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [EL_SESSIONS_SESSION_TOKEN_key] UNIQUE NONCLUSTERED ([SESSION_TOKEN])
);

-- CreateTable
CREATE TABLE [dbo].[EL_USERS] (
    [ID] NVARCHAR(1000) NOT NULL,
    [NAME] NVARCHAR(1000),
    [EMAIL] NVARCHAR(1000),
    [EMAIL_VERIFIED] DATETIME2,
    [IMAGE] NVARCHAR(1000),
    [ROLE] NVARCHAR(1000) NOT NULL CONSTRAINT [EL_USERS_ROLE_df] DEFAULT 'user',
    [EMPLOYEE_ID] NVARCHAR(1000),
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_USERS_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [UPDATED_AT] DATETIME2 NOT NULL,
    CONSTRAINT [EL_USERS_pkey] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [EL_USERS_EMAIL_key] UNIQUE NONCLUSTERED ([EMAIL]),
    CONSTRAINT [EL_USERS_EMPLOYEE_ID_key] UNIQUE NONCLUSTERED ([EMPLOYEE_ID])
);

-- CreateTable
CREATE TABLE [dbo].[EL_VERIFICATION_TOKENS] (
    [IDENTIFIER] NVARCHAR(1000) NOT NULL,
    [TOKEN] NVARCHAR(1000) NOT NULL,
    [EXPIRES] DATETIME2 NOT NULL,
    CONSTRAINT [EL_VERIFICATION_TOKENS_TOKEN_key] UNIQUE NONCLUSTERED ([TOKEN]),
    CONSTRAINT [EL_VERIFICATION_TOKENS_IDENTIFIER_TOKEN_key] UNIQUE NONCLUSTERED ([IDENTIFIER],[TOKEN])
);

-- CreateTable
CREATE TABLE [dbo].[EL_EMPLOYEES] (
    [ID] NVARCHAR(1000) NOT NULL,
    [ID_EMP] NVARCHAR(1000) NOT NULL,
    [NAME] NVARCHAR(1000) NOT NULL,
    [SECTION] NVARCHAR(1000) NOT NULL,
    [DEPARTMENT] NVARCHAR(1000) NOT NULL,
    [COMPANY] NVARCHAR(1000) NOT NULL,
    [PASSWORD] NVARCHAR(1000),
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_EMPLOYEES_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [UPDATED_AT] DATETIME2 NOT NULL,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [EL_EMPLOYEES_pkey] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [EL_EMPLOYEES_ID_EMP_key] UNIQUE NONCLUSTERED ([ID_EMP])
);

-- CreateTable
CREATE TABLE [dbo].[EL_GROUPS] (
    [ID] NVARCHAR(1000) NOT NULL,
    [TITLE] NVARCHAR(1000) NOT NULL,
    [DESCRIPTION] NVARCHAR(1000),
    [ORDER] INT NOT NULL CONSTRAINT [EL_GROUPS_ORDER_df] DEFAULT 0,
    [IS_ACTIVE] BIT NOT NULL CONSTRAINT [EL_GROUPS_IS_ACTIVE_df] DEFAULT 1,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_GROUPS_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [UPDATED_AT] DATETIME2 NOT NULL,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [EL_GROUPS_pkey] PRIMARY KEY CLUSTERED ([ID])
);

-- CreateTable
CREATE TABLE [dbo].[EL_COURSES] (
    [ID] NVARCHAR(1000) NOT NULL,
    [GROUP_ID] NVARCHAR(1000),
    [TITLE] NVARCHAR(1000) NOT NULL,
    [DESCRIPTION] NVARCHAR(1000),
    [CONTENT_TYPE] NVARCHAR(1000) NOT NULL,
    [CONTENT_URL] NVARCHAR(1000),
    [CONTENT_SOURCE] NVARCHAR(1000) NOT NULL CONSTRAINT [EL_COURSES_CONTENT_SOURCE_df] DEFAULT 'url',
    [CONTENT_FILE] NVARCHAR(1000),
    [ORDER] INT NOT NULL CONSTRAINT [EL_COURSES_ORDER_df] DEFAULT 0,
    [IS_ACTIVE] BIT NOT NULL CONSTRAINT [EL_COURSES_IS_ACTIVE_df] DEFAULT 1,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_COURSES_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [UPDATED_AT] DATETIME2 NOT NULL,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [EL_COURSES_pkey] PRIMARY KEY CLUSTERED ([ID])
);

-- CreateTable
CREATE TABLE [dbo].[EL_TESTS] (
    [ID] NVARCHAR(1000) NOT NULL,
    [COURSE_ID] NVARCHAR(1000) NOT NULL,
    [TYPE] NVARCHAR(1000) NOT NULL,
    [TITLE] NVARCHAR(1000) NOT NULL,
    [DESCRIPTION] NVARCHAR(1000),
    [IS_ACTIVE] BIT NOT NULL CONSTRAINT [EL_TESTS_IS_ACTIVE_df] DEFAULT 1,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_TESTS_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [UPDATED_AT] DATETIME2 NOT NULL,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [EL_TESTS_pkey] PRIMARY KEY CLUSTERED ([ID])
);

-- CreateTable
CREATE TABLE [dbo].[EL_QUESTIONS] (
    [ID] NVARCHAR(1000) NOT NULL,
    [TEST_ID] NVARCHAR(1000) NOT NULL,
    [TYPE] NVARCHAR(1000) NOT NULL,
    [QUESTION] NVARCHAR(1000) NOT NULL,
    [OPTIONS] NVARCHAR(1000),
    [CORRECT_ANSWER] NVARCHAR(1000),
    [POINTS] INT NOT NULL CONSTRAINT [EL_QUESTIONS_POINTS_df] DEFAULT 1,
    [ORDER] INT NOT NULL,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_QUESTIONS_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [UPDATED_AT] DATETIME2 NOT NULL,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [EL_QUESTIONS_pkey] PRIMARY KEY CLUSTERED ([ID])
);

-- CreateTable
CREATE TABLE [dbo].[EL_COURSE_ATTEMPTS] (
    [ID] NVARCHAR(1000) NOT NULL,
    [EMPLOYEE_ID] NVARCHAR(1000) NOT NULL,
    [COURSE_ID] NVARCHAR(1000) NOT NULL,
    [STARTED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_COURSE_ATTEMPTS_STARTED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [COMPLETED_AT] DATETIME2,
    [STATUS] NVARCHAR(1000) NOT NULL CONSTRAINT [EL_COURSE_ATTEMPTS_STATUS_df] DEFAULT 'in_progress',
    [CONTENT_STARTED_AT] DATETIME2,
    [CONTENT_COMPLETED_AT] DATETIME2,
    [CONTENT_DURATION] INT,
    [CONTENT_PROGRESS] FLOAT(53) NOT NULL CONSTRAINT [EL_COURSE_ATTEMPTS_CONTENT_PROGRESS_df] DEFAULT 0,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_COURSE_ATTEMPTS_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [UPDATED_AT] DATETIME2 NOT NULL,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [EL_COURSE_ATTEMPTS_pkey] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [EL_COURSE_ATTEMPTS_EMPLOYEE_ID_COURSE_ID_key] UNIQUE NONCLUSTERED ([EMPLOYEE_ID],[COURSE_ID])
);

-- CreateTable
CREATE TABLE [dbo].[EL_TEST_ATTEMPTS] (
    [ID] NVARCHAR(1000) NOT NULL,
    [EMPLOYEE_ID] NVARCHAR(1000) NOT NULL,
    [TEST_ID] NVARCHAR(1000) NOT NULL,
    [STARTED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_TEST_ATTEMPTS_STARTED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [COMPLETED_AT] DATETIME2,
    [SCORE] FLOAT(53),
    [STATUS] NVARCHAR(1000) NOT NULL CONSTRAINT [EL_TEST_ATTEMPTS_STATUS_df] DEFAULT 'in_progress',
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_TEST_ATTEMPTS_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [UPDATED_AT] DATETIME2 NOT NULL,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [EL_TEST_ATTEMPTS_pkey] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [EL_TEST_ATTEMPTS_EMPLOYEE_ID_TEST_ID_key] UNIQUE NONCLUSTERED ([EMPLOYEE_ID],[TEST_ID])
);

-- CreateTable
CREATE TABLE [dbo].[EL_ANSWERS] (
    [ID] NVARCHAR(1000) NOT NULL,
    [TEST_ATTEMPT_ID] NVARCHAR(1000) NOT NULL,
    [QUESTION_ID] NVARCHAR(1000) NOT NULL,
    [ANSWER] NVARCHAR(1000) NOT NULL,
    [IS_CORRECT] BIT,
    [POINTS] FLOAT(53) NOT NULL CONSTRAINT [EL_ANSWERS_POINTS_df] DEFAULT 0,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_ANSWERS_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [UPDATED_AT] DATETIME2 NOT NULL,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [EL_ANSWERS_pkey] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [EL_ANSWERS_TEST_ATTEMPT_ID_QUESTION_ID_key] UNIQUE NONCLUSTERED ([TEST_ATTEMPT_ID],[QUESTION_ID])
);

-- CreateTable
CREATE TABLE [dbo].[EL_SCORES] (
    [ID] NVARCHAR(1000) NOT NULL,
    [EMPLOYEE_ID] NVARCHAR(1000) NOT NULL,
    [COURSE_ID] NVARCHAR(1000) NOT NULL,
    [PRE_TEST_SCORE] FLOAT(53),
    [POST_TEST_SCORE] FLOAT(53),
    [FINAL_SCORE] FLOAT(53),
    [COMPLETED_AT] DATETIME2,
    [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [EL_SCORES_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
    [UPDATED_AT] DATETIME2 NOT NULL,
    [DELETED_AT] DATETIME2,
    CONSTRAINT [EL_SCORES_pkey] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [EL_SCORES_EMPLOYEE_ID_COURSE_ID_key] UNIQUE NONCLUSTERED ([EMPLOYEE_ID],[COURSE_ID])
);

-- AddForeignKey
ALTER TABLE [dbo].[EL_ACCOUNTS] ADD CONSTRAINT [EL_ACCOUNTS_USER_ID_fkey] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[EL_USERS]([ID]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EL_SESSIONS] ADD CONSTRAINT [EL_SESSIONS_USER_ID_fkey] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[EL_USERS]([ID]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EL_USERS] ADD CONSTRAINT [EL_USERS_EMPLOYEE_ID_fkey] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [dbo].[EL_EMPLOYEES]([ID]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EL_COURSES] ADD CONSTRAINT [EL_COURSES_GROUP_ID_fkey] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[EL_GROUPS]([ID]) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EL_TESTS] ADD CONSTRAINT [EL_TESTS_COURSE_ID_fkey] FOREIGN KEY ([COURSE_ID]) REFERENCES [dbo].[EL_COURSES]([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[EL_QUESTIONS] ADD CONSTRAINT [EL_QUESTIONS_TEST_ID_fkey] FOREIGN KEY ([TEST_ID]) REFERENCES [dbo].[EL_TESTS]([ID]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EL_COURSE_ATTEMPTS] ADD CONSTRAINT [EL_COURSE_ATTEMPTS_EMPLOYEE_ID_fkey] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [dbo].[EL_EMPLOYEES]([ID]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EL_COURSE_ATTEMPTS] ADD CONSTRAINT [EL_COURSE_ATTEMPTS_COURSE_ID_fkey] FOREIGN KEY ([COURSE_ID]) REFERENCES [dbo].[EL_COURSES]([ID]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EL_TEST_ATTEMPTS] ADD CONSTRAINT [EL_TEST_ATTEMPTS_EMPLOYEE_ID_fkey] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [dbo].[EL_EMPLOYEES]([ID]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EL_TEST_ATTEMPTS] ADD CONSTRAINT [EL_TEST_ATTEMPTS_TEST_ID_fkey] FOREIGN KEY ([TEST_ID]) REFERENCES [dbo].[EL_TESTS]([ID]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EL_ANSWERS] ADD CONSTRAINT [EL_ANSWERS_TEST_ATTEMPT_ID_fkey] FOREIGN KEY ([TEST_ATTEMPT_ID]) REFERENCES [dbo].[EL_TEST_ATTEMPTS]([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[EL_ANSWERS] ADD CONSTRAINT [EL_ANSWERS_QUESTION_ID_fkey] FOREIGN KEY ([QUESTION_ID]) REFERENCES [dbo].[EL_QUESTIONS]([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[EL_SCORES] ADD CONSTRAINT [EL_SCORES_EMPLOYEE_ID_fkey] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [dbo].[EL_EMPLOYEES]([ID]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[EL_SCORES] ADD CONSTRAINT [EL_SCORES_COURSE_ID_fkey] FOREIGN KEY ([COURSE_ID]) REFERENCES [dbo].[EL_COURSES]([ID]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
