-- Add database indexes for better progress query performance
-- Run this after your next migration

-- Index for finding course attempts by employee and course
CREATE INDEX IX_EL_COURSE_ATTEMPTS_EMPLOYEE_COURSE 
ON EL_COURSE_ATTEMPTS (EMPLOYEE_ID, COURSE_ID) 
WHERE DELETED_AT IS NULL;

-- Index for progress reporting queries
CREATE INDEX IX_EL_COURSE_ATTEMPTS_PROGRESS 
ON EL_COURSE_ATTEMPTS (EMPLOYEE_ID, CONTENT_PROGRESS, STATUS) 
WHERE DELETED_AT IS NULL;

-- Index for active course attempts
CREATE INDEX IX_EL_COURSE_ATTEMPTS_ACTIVE 
ON EL_COURSE_ATTEMPTS (STATUS, UPDATED_AT) 
WHERE DELETED_AT IS NULL;

-- Index for completion tracking
CREATE INDEX IX_EL_COURSE_ATTEMPTS_COMPLETION 
ON EL_COURSE_ATTEMPTS (COURSE_ID, STATUS, COMPLETED_AT) 
WHERE DELETED_AT IS NULL;

-- Index for score tracking queries
CREATE INDEX IX_EL_SCORES_EMPLOYEE_COURSE 
ON EL_SCORES (EMPLOYEE_ID, COURSE_ID) 
WHERE DELETED_AT IS NULL;

-- Index for enrollment progress queries
CREATE INDEX IX_EL_COURSE_ENROLLMENTS_ACTIVE 
ON EL_COURSE_ENROLLMENTS (EMPLOYEE_ID, STATUS) 
WHERE DELETED_AT IS NULL;

-- Statistics for query optimizer
UPDATE STATISTICS EL_COURSE_ATTEMPTS;
UPDATE STATISTICS EL_SCORES;
UPDATE STATISTICS EL_COURSE_ENROLLMENTS;