BEGIN TRY

BEGIN TRAN;

-- Rename tables to add EL_ prefix
EXEC sp_rename 'ACCOUNTS', 'EL_ACCOUNTS';
EXEC sp_rename 'SESSIONS', 'EL_SESSIONS';
EXEC sp_rename 'USERS', 'EL_USERS';
EXEC sp_rename 'VERIFICATION_TOKENS', 'EL_VERIFICATION_TOKENS';
EXEC sp_rename 'EMPLOYEES', 'EL_EMPLOYEES';
EXEC sp_rename 'COURSES', 'EL_COURSES';
EXEC sp_rename 'TESTS', 'EL_TESTS';
EXEC sp_rename 'QUESTIONS', 'EL_QUESTIONS';
EXEC sp_rename 'COURSE_ATTEMPTS', 'EL_COURSE_ATTEMPTS';
EXEC sp_rename 'TEST_ATTEMPTS', 'EL_TEST_ATTEMPTS';
EXEC sp_rename 'ANSWERS', 'EL_ANSWERS';
EXEC sp_rename 'SCORES', 'EL_SCORES';

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH